export const GET_FRIENDS_LIST_SUCCESS = 'GET_FRIENDS_LIST_SUCCESS';
export const GET_FRIENDS_LIST_FAIL = 'GET_FRIENDS_LIST_FAIL';
export const GET_FRIEND_REQUESTS_LIST_SUCCESS = 'GET_FRIEND_REQUESTS_LIST_SUCCESS';
export const GET_FRIEND_REQUESTS_LIST_FAIL = 'GET_FRIEND_REQUESTS_LIST_FAIL';
export const CONNECT_WEBSOCKET = 'CONNECT_WEBSOCKET';
export const DISCONNECT_WEBSOCKET = 'DISCONNECT_WEBSOCKET';
