export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';

export const DEPLOY_COURSE_SUCCESS = 'DEPLOY_COURSE_SUCCESS';
export const DEPLOY_COURSE_FAIL = 'DEPLOY_COURSE_FAIL';

export const ADD_WHATLEARNT = 'ADD_WHATLEARNT';
export const REMOVE_WHATLEARNT = 'REMOVE_WHATLEARNT';
export const ON_CHANGE_COURSE_WHATLEARNT = 'ON_CHANGE_COURSE_WHATLEARNT';
export const UPDATE_DRAGGABLES_WHATLEARNT = 'UPDATE_DRAGGABLES_WHATLEARNT';

export const ADD_REQUISITE = 'ADD_REQUISITE';
export const REMOVE_REQUISITE = 'REMOVE_REQUISITE';
export const ON_CHANGE_COURSE_REQUISITE = 'ON_CHANGE_COURSE_REQUISITE';
export const UPDATE_DRAGGABLES_REQUISITE = 'UPDATE_DRAGGABLES_REQUISITE';

export const ADD_WHOISFOR = 'ADD_WHOISFOR';
export const REMOVE_WHOISFOR = 'REMOVE_WHOISFOR';
export const ON_CHANGE_COURSE_WHOISFOR = 'ON_CHANGE_COURSE_WHOISFOR';
export const UPDATE_DRAGGABLES_WHOISFOR = 'UPDATE_DRAGGABLES_WHOISFOR';

export const ON_CHANGE_COURSE_TITLE = 'ON_CHANGE_COURSE_TITLE';
export const ON_CHANGE_COURSE_SUB_TITLE = 'ON_CHANGE_COURSE_SUB_TITLE';
export const ON_CHANGE_COURSE_DESCRIPTION = 'ON_CHANGE_COURSE_DESCRIPTION';
export const ON_CHANGE_COURSE_TAUGHT = 'ON_CHANGE_COURSE_TAUGHT';
export const ON_CHANGE_COURSE_LANGUAGE = 'ON_CHANGE_COURSE_LANGUAGE';
export const ON_CHANGE_COURSE_LEVEL = 'ON_CHANGE_COURSE_LEVEL';
export const ON_CHANGE_COURSE_CATEGORY = 'ON_CHANGE_COURSE_CATEGORY';

export const IMAGE_UPLOADED_SUCCESS = 'IMAGE_UPLOADED_SUCCESS';
export const IMAGE_UPLOADED_FAIL = 'IMAGE_UPLOADED_FAIL';

export const VIDEO_UPLOADED_SUCCESS = 'VIDEO_UPLOADED_SUCCESS';
export const VIDEO_UPLOADED_FAIL = 'VIDEO_UPLOADED_FAIL';

export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const ON_CHANGE_COURSE_IMAGE = 'ON_CHANGE_COURSE_IMAGE';
export const UPDATE_DRAGGABLES_IMAGE = 'UPDATE_DRAGGABLES_IMAGE';

export const ADD_VIDEO = 'ADD_VIDEO';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const ON_CHANGE_COURSE_VIDEO = 'ON_CHANGE_COURSE_VIDEO';
export const UPDATE_DRAGGABLES_VIDEO = 'UPDATE_DRAGGABLES_VIDEO';

export const ON_CHANGE_COURSE_PRICE = 'ON_CHANGE_COURSE_PRICE';
export const ON_CHANGE_COURSE_COMPARE_PRICE = 'ON_CHANGE_COURSE_COMPARE_PRICE';
export const ON_CHANGE_COURSE_DISCOUNT_UNTIL = 'ON_CHANGE_COURSE_DISCOUNT_UNTIL';

export const ON_CHANGE_COURSE_WELCOME_MESSAGE = 'ON_CHANGE_COURSE_WELCOME_MESSAGE';
export const ON_CHANGE_COURSE_CONGRATS_MESSAGE = 'ON_CHANGE_COURSE_CONGRATS_MESSAGE';

export const RESET_CREATE_VARIABLES = 'RESET_CREATE_VARIABLES';
