# Generated by Django 3.2.16 on 2023-04-06 19:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230406_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=9, null=True),
        ),
    ]
