# Generated by Django 3.2.16 on 2023-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='orders/thumbnails'),
        ),
    ]
