# Generated by Django 3.2.16 on 2023-04-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='orders/thumbnails'),
        ),
    ]
