# Generated by Django 3.2.16 on 2023-02-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='object_price',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
