// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REMOVE_CTA_BANNER = 'REMOVE_CTA_BANNER';
export const REMOVE_DISCOUNT_BANNER = 'REMOVE_DISCOUNT_BANNER';
