version: '3.8'
services:
  # Django app
  backend_orders:
    container_name: boomslag_ms_orders
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8008"
    volumes:
      - .:/app
    ports:
      - 8008:8008
  # Event Queue Kafka
  queue_orders:
    build: .
    command: >
      sh -c "python consumer.py"