export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const EDIT_GOALS_WHATLEARNT_SUCCESS = 'EDIT_GOALS_WHATLEARNT_SUCCESS';
export const EDIT_GOALS_WHATLEARNT_FAIL = 'EDIT_GOALS_WHATLEARNT_FAIL';
export const ONCHANGE_GOALS_WHATLEARNT_SUCCESS = 'ONCHANGE_GOALS_WHATLEARNT_SUCCESS';
export const ONCHANGE_GOALS_WHATLEARNT_FAIL = 'ONCHANGE_GOALS_WHATLEARNT_FAIL';
export const EDIT_GOALS_REQUIREMENTS_SUCCESS = 'EDIT_GOALS_REQUIREMENTS_SUCCESS';
export const EDIT_GOALS_REQUIREMENTS_FAIL = 'EDIT_GOALS_REQUIREMENTS_FAIL';
export const ONCHANGE_GOALS_REQUIREMENTS_SUCCESS = 'ONCHANGE_GOALS_REQUIREMENTS_SUCCESS';
export const ONCHANGE_GOALS_REQUIREMENTS_FAIL = 'ONCHANGE_GOALS_REQUIREMENTS_FAIL';
export const EDIT_GOALS_WHOISFOR_SUCCESS = 'EDIT_GOALS_WHOISFOR_SUCCESS';
export const EDIT_GOALS_WHOISFOR_FAIL = 'EDIT_GOALS_WHOISFOR_FAIL';
export const ONCHANGE_GOALS_WHOISFOR_SUCCESS = 'ONCHANGE_GOALS_WHOISFOR_SUCCESS';
export const ONCHANGE_GOALS_WHOISFOR_FAIL = 'ONCHANGE_GOALS_WHOISFOR_FAIL';

export const SET_TARGET_AUDIENCE_SUCCESS = 'SET_TARGET_AUDIENCE_SUCCESS';
export const SET_TARGET_AUDIENCE_FAIL = 'SET_TARGET_AUDIENCE_FAIL';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';

export const SET_PRODUCT_UUID = 'SET_PRODUCT_UUID';

export const ONCHANGE_PRODUCT_TITLE_SUCCESS = 'ONCHANGE_PRODUCT_TITLE_SUCCESS';
export const ONCHANGE_PRODUCT_TITLE_FAIL = 'ONCHANGE_PRODUCT_TITLE_FAIL';
export const ONCHANGE_PRODUCT_SUB_TITLE_SUCCESS = 'ONCHANGE_PRODUCT_SUB_TITLE_SUCCESS';
export const ONCHANGE_PRODUCT_SUB_TITLE_FAIL = 'ONCHANGE_PRODUCT_SUB_TITLE_FAIL';
export const ONCHANGE_PRODUCT_DESCRIPTION_SUCCESS = 'ONCHANGE_PRODUCT_DESCRIPTION_SUCCESS';
export const ONCHANGE_PRODUCT_DESCRIPTION_FAIL = 'ONCHANGE_PRODUCT_DESCRIPTION_FAIL';
export const ONCHANGE_PRODUCT_LANGUAGE_SUCCESS = 'ONCHANGE_PRODUCT_LANGUAGE_SUCCESS';
export const ONCHANGE_PRODUCT_LANGUAGE_FAIL = 'ONCHANGE_PRODUCT_LANGUAGE_FAIL';
export const ONCHANGE_PRODUCT_LEVEL_SUCCESS = 'ONCHANGE_PRODUCT_LEVEL_SUCCESS';
export const ONCHANGE_PRODUCT_LEVEL_FAIL = 'ONCHANGE_PRODUCT_LEVEL_FAIL';
export const ONCHANGE_PRODUCT_CATEGORY_SUCCESS = 'ONCHANGE_PRODUCT_CATEGORY_SUCCESS';
export const ONCHANGE_PRODUCT_CATEGORY_FAIL = 'ONCHANGE_PRODUCT_CATEGORY_FAIL';
export const ONCHANGE_PRODUCT_STOCK_SUCCESS = 'ONCHANGE_PRODUCT_STOCK_SUCCESS';
export const ONCHANGE_PRODUCT_STOCK_FAIL = 'ONCHANGE_PRODUCT_STOCK_FAIL';
export const ONCHANGE_PRODUCT_IMAGE_SUCCESS = 'ONCHANGE_PRODUCT_IMAGE_SUCCESS';
export const ONCHANGE_PRODUCT_IMAGE_FAIL = 'ONCHANGE_PRODUCT_IMAGE_FAIL';
export const ONCHANGE_PRODUCT_IMAGE_FILENAME_SUCCESS = 'ONCHANGE_PRODUCT_IMAGE_FILENAME_SUCCESS';
export const ONCHANGE_PRODUCT_IMAGE_FILENAME_FAIL = 'ONCHANGE_PRODUCT_IMAGE_FILENAME_FAIL';
export const ONCHANGE_PRODUCT_VIDEO_SUCCESS = 'ONCHANGE_PRODUCT_VIDEO_SUCCESS';
export const ONCHANGE_PRODUCT_VIDEO_FAIL = 'ONCHANGE_PRODUCT_VIDEO_FAIL';
export const ONCHANGE_PRODUCT_VIDEO_FILENAME_SUCCESS = 'ONCHANGE_PRODUCT_VIDEO_FILENAME_SUCCESS';
export const ONCHANGE_PRODUCT_VIDEO_FILENAME_FAIL = 'ONCHANGE_PRODUCT_VIDEO_FILENAME_FAIL';
export const PERCENTAGE_SALES_VIDEO_UPLOAD = 'PERCENTAGE_SALES_VIDEO_UPLOAD';
export const PERCENTAGE_THUMBNAIL_UPLOAD = 'PERCENTAGE_THUMBNAIL_UPLOAD';
export const IMAGE_UPLOADED_SUCCESS = 'IMAGE_UPLOADED_SUCCESS';
export const IMAGE_UPLOADED_FAIL = 'IMAGE_UPLOADED_FAIL';
export const VIDEO_UPLOADED_SUCCESS = 'VIDEO_UPLOADED_SUCCESS';
export const VIDEO_UPLOADED_FAIL = 'VIDEO_UPLOADED_FAIL';

export const ONCHANGE_CONGRATS_MESSAGE_SUCCESS = 'ONCHANGE_CONGRATS_MESSAGE_SUCCESS';
export const ONCHANGE_CONGRATS_MESSAGE_FAIL = 'ONCHANGE_CONGRATS_MESSAGE_FAIL';

export const ONCHANGE_WELCOME_MESSAGE_SUCCESS = 'ONCHANGE_WELCOME_MESSAGE_SUCCESS';
export const ONCHANGE_WELCOME_MESSAGE_FAIL = 'ONCHANGE_WELCOME_MESSAGE_FAIL';

export const ONCHANGE_PRODUCT_DETAILS_SUCCESS = 'ONCHANGE_PRODUCT_DETAILS_SUCCESS';
export const ONCHANGE_PRODUCT_DETAILS_FAIL = 'ONCHANGE_PRODUCT_DETAILS_FAIL';
export const ONCHANGE_PRODUCT_SIZE_SUCCESS = 'ONCHANGE_PRODUCT_SIZE_SUCCESS';
export const ONCHANGE_PRODUCT_SIZE_FAIL = 'ONCHANGE_PRODUCT_SIZE_FAIL';
export const ONCHANGE_PRODUCT_COLORS_SUCCESS = 'ONCHANGE_PRODUCT_COLORS_SUCCESS';
export const ONCHANGE_PRODUCT_COLORS_FAIL = 'ONCHANGE_PRODUCT_COLORS_FAIL';

export const ADD_SIZE = 'ADD_SIZE';
export const REMOVE_SIZE = 'REMOVE_SIZE';
export const ON_CHANGE_PRODUCT_SIZES = 'ON_CHANGE_PRODUCT_SIZES';
export const UPDATE_DRAGGABLES_SIZE = 'UPDATE_DRAGGABLES_SIZE';

export const ADD_WHATLEARNT = 'ADD_WHATLEARNT';
export const REMOVE_WHATLEARNT = 'REMOVE_WHATLEARNT';
export const ON_CHANGE_PRODUCT_WHATLEARNT = 'ON_CHANGE_PRODUCT_WHATLEARNT';
export const UPDATE_DRAGGABLES_WHATLEARNT = 'UPDATE_DRAGGABLES_WHATLEARNT';

export const ADD_WHOISFOR = 'ADD_WHOISFOR';
export const REMOVE_WHOISFOR = 'REMOVE_WHOISFOR';
export const ON_CHANGE_PRODUCT_WHOISFOR = 'ON_CHANGE_PRODUCT_WHOISFOR';
export const UPDATE_DRAGGABLES_WHOISFOR = 'UPDATE_DRAGGABLES_WHOISFOR';

export const ADD_REQUISITE = 'ADD_REQUISITE';
export const REMOVE_REQUISITE = 'REMOVE_REQUISITE';
export const ON_CHANGE_PRODUCT_REQUISITE = 'ON_CHANGE_PRODUCT_REQUISITE';
export const UPDATE_DRAGGABLES_REQUISITE = 'UPDATE_DRAGGABLES_REQUISITE';

export const ADD_COLOR = 'ADD_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const ON_CHANGE_PRODUCT_COLOR = 'ON_CHANGE_PRODUCT_COLOR';
export const UPDATE_DRAGGABLES_COLOR = 'UPDATE_DRAGGABLES_COLOR';

export const ADD_WEIGHT = 'ADD_WEIGHT';
export const REMOVE_WEIGHT = 'REMOVE_WEIGHT';
export const ON_CHANGE_PRODUCT_WEIGHT = 'ON_CHANGE_PRODUCT_WEIGHT';
export const UPDATE_DRAGGABLES_WEIGHT = 'UPDATE_DRAGGABLES_WEIGHT';

export const ADD_MATERIAL = 'ADD_MATERIAL';
export const REMOVE_MATERIAL = 'REMOVE_MATERIAL';
export const ON_CHANGE_PRODUCT_MATERIAL = 'ON_CHANGE_PRODUCT_MATERIAL';
export const UPDATE_DRAGGABLES_MATERIAL = 'UPDATE_DRAGGABLES_MATERIAL';

export const ADD_SHIPPING = 'ADD_SHIPPING';
export const REMOVE_SHIPPING = 'REMOVE_SHIPPING';
export const ON_CHANGE_PRODUCT_SHIPPING = 'ON_CHANGE_PRODUCT_SHIPPING';
export const UPDATE_DRAGGABLES_SHIPPING = 'UPDATE_DRAGGABLES_SHIPPING';

export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const ON_CHANGE_PRODUCT_IMAGE = 'ON_CHANGE_PRODUCT_IMAGE';
export const UPDATE_DRAGGABLES_IMAGE = 'UPDATE_DRAGGABLES_IMAGE';

export const ADD_VIDEO = 'ADD_VIDEO';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const ON_CHANGE_PRODUCT_VIDEO = 'ON_CHANGE_PRODUCT_VIDEO';
export const UPDATE_DRAGGABLES_VIDEO = 'UPDATE_DRAGGABLES_VIDEO';

export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT';
export const ON_CHANGE_PRODUCT_DOCUMENT = 'ON_CHANGE_PRODUCT_DOCUMENT';
export const UPDATE_DRAGGABLES_DOCUMENT = 'UPDATE_DRAGGABLES_DOCUMENT';

export const ADD_RESOURCE = 'ADD_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const ON_CHANGE_PRODUCT_RESOURCE = 'ON_CHANGE_PRODUCT_RESOURCE';
export const UPDATE_DRAGGABLES_RESOURCE = 'UPDATE_DRAGGABLES_RESOURCE';

export const ADD_DETAIL = 'ADD_DETAIL';
export const REMOVE_DETAIL = 'REMOVE_DETAIL';
export const ON_CHANGE_PRODUCT_DETAIL = 'ON_CHANGE_PRODUCT_DETAIL';
export const UPDATE_DRAGGABLES_DETAIL = 'UPDATE_DRAGGABLES_DETAIL';

export const RESET_CREATE_VARIABLES = 'RESET_CREATE_VARIABLES';

export const EDIT_PRODUCT_DETAILS_SUCCESS = 'EDIT_PRODUCT_DETAILS_SUCCESS';
export const EDIT_PRODUCT_DETAILS_FAIL = 'EDIT_PRODUCT_DETAILS_FAIL';
export const EDIT_PRODUCT_SIZES_SUCCESS = 'EDIT_PRODUCT_SIZES_SUCCESS';
export const EDIT_PRODUCT_SIZES_FAIL = 'EDIT_PRODUCT_SIZES_FAIL';
export const EDIT_PRODUCT_COLORS_SUCCESS = 'EDIT_PRODUCT_COLORS_SUCCESS';
export const EDIT_PRODUCT_COLORS_FAIL = 'EDIT_PRODUCT_COLORS_FAIL';
export const EDIT_PRODUCT_DOCUMENTS_SUCCESS = 'EDIT_PRODUCT_DOCUMENTS_SUCCESS';
export const EDIT_PRODUCT_DOCUMENTS_FAIL = 'EDIT_PRODUCT_DOCUMENTS_FAIL';
export const EDIT_PRODUCT_IMAGES_SUCCESS = 'EDIT_PRODUCT_IMAGES_SUCCESS';
export const EDIT_PRODUCT_IMAGES_FAIL = 'EDIT_PRODUCT_IMAGES_FAIL';
export const EDIT_PRODUCT_VIDEOS_SUCCESS = 'EDIT_PRODUCT_VIDEOS_SUCCESS';
export const EDIT_PRODUCT_VIDEOS_FAIL = 'EDIT_PRODUCT_VIDEOS_FAIL';
export const EDIT_PRODUCT_SHIPPING_SUCCESS = 'EDIT_PRODUCT_SHIPPING_SUCCESS';
export const EDIT_PRODUCT_SHIPPING_FAIL = 'EDIT_PRODUCT_SHIPPING_FAIL';
export const EDIT_PRODUCT_WEIGTH_SUCCESS = 'EDIT_PRODUCT_WEIGTH_SUCCESS';
export const EDIT_PRODUCT_WEIGTH_FAIL = 'EDIT_PRODUCT_WEIGTH_FAIL';

export const ON_CHANGE_PRODUCT_PRICE = 'ON_CHANGE_PRODUCT_PRICE';
export const ON_CHANGE_PRODUCT_COMPARE_PRICE = 'ON_CHANGE_PRODUCT_COMPARE_PRICE';
export const ON_CHANGE_PRODUCT_DISCOUNT_UNTIL = 'ON_CHANGE_PRODUCT_DISCOUNT_UNTIL';
export const ONCHANGE_PRODUCT_PRICE_FAIL = 'ONCHANGE_PRODUCT_PRICE_FAIL';
export const ONCHANGE_PRODUCT_COMPARE_PRICE_SUCCESS = 'ONCHANGE_PRODUCT_COMPARE_PRICE_SUCCESS';
export const ONCHANGE_PRODUCT_COMPARE_PRICE_FAIL = 'ONCHANGE_PRODUCT_COMPARE_PRICE_FAIL';
export const ONCHANGE_PRODUCT_DISCOUNT_PRICE_SUCCESS = 'ONCHANGE_PRODUCT_DISCOUNT_PRICE_SUCCESS';
export const ONCHANGE_PRODUCT_DISCOUNT_PRICE_FAIL = 'ONCHANGE_PRODUCT_DISCOUNT_PRICE_FAIL';
