# Generated by Django 3.2.16 on 2023-01-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
