# Generated by Django 3.2.16 on 2023-01-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230124_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
