# Generated by Django 3.2.16 on 2023-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clickThroughRate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='impressions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
