# Generated by Django 3.2.16 on 2023-02-06 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
