# Generated by Django 3.2.16 on 2023-04-04 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20230403_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.UUIDField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('polygon_address', models.CharField(blank=True, max_length=256, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSeller', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(blank=True, related_name='courseSellers', to='product.Sellers'),
        ),
    ]
