// Authentication
export const EDIT_USERNAME_SUCCESS = 'EDIT_USERNAME_SUCCESS';
export const EDIT_USERNAME_FAIL = 'EDIT_USERNAME_FAIL';

export const EDIT_PICTURE_SUCCESS = 'EDIT_PICTURE_SUCCESS';
export const EDIT_PICTURE_FAIL = 'EDIT_PICTURE_FAIL';

export const EDIT_BANNER_SUCCESS = 'EDIT_BANNER_SUCCESS';
export const EDIT_BANNER_FAIL = 'EDIT_BANNER_FAIL';

export const EDIT_FIRST_NAME_SUCCESS = 'EDIT_FIRST_NAME_SUCCESS';
export const EDIT_FIRST_NAME_FAIL = 'EDIT_FIRST_NAME_FAIL';

export const EDIT_LAST_NAME_SUCCESS = 'EDIT_LAST_NAME_SUCCESS';
export const EDIT_LAST_NAME_FAIL = 'EDIT_LAST_NAME_FAIL';

export const EDIT_LOCATION_SUCCESS = 'EDIT_LOCATION_SUCCESS';
export const EDIT_LOCATION_FAIL = 'EDIT_LOCATION_FAIL';

export const EDIT_URL_SUCCESS = 'EDIT_URL_SUCCESS';
export const EDIT_URL_FAIL = 'EDIT_URL_FAIL';

export const EDIT_BIRTHDAY_SUCCESS = 'EDIT_BIRTHDAY_SUCCESS';
export const EDIT_BIRTHDAY_FAIL = 'EDIT_BIRTHDAY_FAIL';

export const EDIT_BIO_SUCCESS = 'EDIT_BIO_SUCCESS';
export const EDIT_BIO_FAIL = 'EDIT_BIO_FAIL';

export const EDIT_FACEBOOK_SUCCESS = 'EDIT_FACEBOOK_SUCCESS';
export const EDIT_FACEBOOK_FAIL = 'EDIT_FACEBOOK_FAIL';

export const EDIT_TWITTER_SUCCESS = 'EDIT_TWITTER_SUCCESS';
export const EDIT_TWITTER_FAIL = 'EDIT_TWITTER_FAIL';

export const EDIT_INSTAGRAM_SUCCESS = 'EDIT_INSTAGRAM_SUCCESS';
export const EDIT_INSTAGRAM_FAIL = 'EDIT_INSTAGRAM_FAIL';

export const EDIT_YOUTUBE_SUCCESS = 'EDIT_YOUTUBE_SUCCESS';
export const EDIT_YOUTUBE_FAIL = 'EDIT_YOUTUBE_FAIL';

export const EDIT_LINKEDIN_SUCCESS = 'EDIT_LINKEDIN_SUCCESS';
export const EDIT_LINKEDIN_FAIL = 'EDIT_LINKEDIN_FAIL';

export const EDIT_GITHUB_SUCCESS = 'EDIT_GITHUB_SUCCESS';
export const EDIT_GITHUB_FAIL = 'EDIT_GITHUB_FAIL';
