export const GET_COUPON_SUCCESS = 'GET_COUPON_SUCCESS';
export const GET_COUPON_FAIL = 'GET_COUPON_FAIL';
export const LIST_COUPONS_SUCCESS = 'LIST_COUPONS_SUCCESS';
export const LIST_COUPONS_FAIL = 'LIST_COUPONS_FAIL';
export const UPDATE_COUPON_PRICE = 'UPDATE_COUPON_PRICE';
