// Teacher Courses
export const GET_ETHEREUM_PRICE_SUCCESS = 'GET_ETHEREUM_PRICE_SUCCESS';
export const GET_ETHEREUM_PRICE_FAIL = 'GET_ETHEREUM_PRICE_FAIL';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';
export const SEND_ETHEREUM_SUCCESS = 'SEND_ETHEREUM_SUCCESS';
export const SEND_ETHEREUM_FAIL = 'SEND_ETHEREUM_FAIL';
export const GET_CARDANO_PRICE_SUCCESS = 'GET_CARDANO_PRICE_SUCCESS';
export const GET_CARDANO_PRICE_FAIL = 'GET_CARDANO_PRICE_FAIL';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';
export const LOAD_SEND_TOKEN_BALANCE_SUCCESS = 'LOAD_SEND_TOKEN_BALANCE_SUCCESS';
export const LOAD_SEND_TOKEN_BALANCE_FAIL = 'LOAD_SEND_TOKEN_BALANCE_FAIL';
// Authentication
export const GET_TOKENS_SUCCESS = 'GET_TOKENS_SUCCESS';
export const GET_TOKENS_FAIL = 'GET_TOKENS_FAIL';
export const GET_TOKENS_COUNT_SUCCESS = 'GET_TOKENS_COUNT_SUCCESS';
export const GET_TOKENS_COUNT_FAIL = 'GET_TOKENS_COUNT_FAIL';
export const GET_POLYGON_TOKENS_SUCCESS = 'GET_POLYGON_TOKENS_SUCCESS';
export const GET_POLYGON_TOKENS_FAIL = 'GET_POLYGON_TOKENS_FAIL';
export const GET_POLYGON_TOKENS_COUNT_SUCCESS = 'GET_POLYGON_TOKENS_COUNT_SUCCESS';
export const GET_POLYGON_TOKENS_COUNT_FAIL = 'GET_POLYGON_TOKENS_COUNT_FAIL';

export const SEND_TOKENS_SUCCESS = 'SEND_TOKENS_SUCCESS';
export const SEND_TOKENS_FAIL = 'SEND_TOKENS_FAIL';
export const SET_SENDING_TOKENS = 'SET_SENDING_TOKENS';
