version: '3.8'
services:
  # Django app
  backend_products:
    container_name: boomslag_ms_products
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/app
    ports:
      - 8003:8003
  # Event Queue Kafka
  queue_products:
    build: .
    command: >
      sh -c "python consumer.py"