// Payments
export const GET_PAYMENT_TOTAL_SUCCESS = 'GET_PAYMENT_TOTAL_SUCCESS';
export const GET_PAYMENT_TOTAL_FAIL = 'GET_PAYMENT_TOTAL_FAIL';
export const LOAD_BT_TOKEN_SUCCESS = 'LOAD_BT_TOKEN_SUCCESS';
export const LOAD_BT_TOKEN_FAIL = 'LOAD_BT_TOKEN_FAIL';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';
export const RESET_PAYMENT_INFO = 'RESET_PAYMENT_INFO';
export const SET_PAYMENT_LOADING = 'SET_PAYMENT_LOADING';
export const REMOVE_PAYMENT_LOADING = 'REMOVE_PAYMENT_LOADING';
export const CREATE_STRIPE_PAYMENT_INTENT_SUCCESS = 'CREATE_STRIPE_PAYMENT_INTENT_SUCCESS';
export const CREATE_STRIPE_PAYMENT_INTENT_FAIL = 'CREATE_STRIPE_PAYMENT_INTET_FAIL';
export const CREATE_STRIPE_GAME_PAYMENT_INTENT_SUCCESS =
  'CREATE_STRIPE_GAME_PAYMENT_INTENT_SUCCESS';
export const CREATE_STRIPE_GAME_PAYMENT_INTENT_FAIL = 'CREATE_STRIPE_GAME_PAYMENT_INTET_FAIL';
export const MADE_STRIPE_PAYMENT = 'MADE_STRIPE_PAYMENT';
