version: '3.8'
services:
  # Django app
  backend_coupons:
    container_name: boomslag_ms_coupons
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8017"
    volumes:
      - .:/app
    ports:
      - 8017:8017
  # # Event Queue Kafka
  # queue_coupons:
  #   build: .
  #   command: >
  #     sh -c "python consumer.py"