export const categories = {
  categories: [
    {
      id: 1,
      name: 'Development',
      title: 'Grow your software development skills',
      description:
        'Learn to build software from scratch, acquire skills in Python, Javascript, React, Machine Learnning ang much more!',
      slug: 'development',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [
        {
          id: 14,
          name: 'Web Development',
          title: 'Learn the Art of Web Development and Build Your Own Web Applications',
          description:
            '"Learn the art of web development and build your own web applications with our comprehensive online courses. From HTML, CSS and JavaScript to backend development and web design, our expert instructors will teach you how to create dynamic and responsive websites that meet the needs of users.',
          slug: 'web-development',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 15,
              name: 'Javascript',
              title: 'Grow your software development skills with JavaScript',
              description:
                'JavaScript is a text-based computer programming language used to make dynamic web pages. A must-learn for aspiring web developers or programmers, JavaScript can be used for features like image carousels, displaying countdowns and timers, and playing media on a webpage.',
              slug: 'javascript',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 16,
              name: 'React',
              title: 'A JavaScript library for building user interfaces',
              description:
                'React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.',
              slug: 'react',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 17,
              name: 'CSS',
              title: 'Learn the Art of Styling and Designing Websites',
              description:
                '"Learn how to style and design professional-looking websites with CSS. Our comprehensive online courses will teach you the latest techniques and best practices for using Cascading Style Sheets, including layout, typography, and responsive design. From basic to advanced CSS, our expert instructors will guide you in mastering the skills you need to create visually stunning websites that stand out from the crowd.',
              slug: 'css',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 18,
              name: 'Typescript',
              title:
                'TypeScript Triumph: Learn to Build Large Scale Applications with a Strongly-typed Language',
              description:
                '"Unlock the power of TypeScript to build large scale, maintainable and robust applications. Our comprehensive online courses will teach you how to use TypeScript\'s advanced features such as classes, interfaces, and decorators, to create scalable and efficient code. Our expert instructors will guide you in mastering the skills you need to develop high-performance web and mobile applications with TypeScript.',
              slug: 'typescript',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 19,
              name: 'HTML5',
              title:
                'HTML5 Mastery: Learn the Fundamentals of Web Development and Build Dynamic Websites',
              description:
                '"Master the fundamentals of web development and build dynamic websites with HTML5. Our comprehensive online courses will teach you the latest techniques and best practices for using HTML5, including semantic structure, multimedia, and forms. From basic to advanced HTML5, our expert instructors will guide you in mastering the skills you need to create responsive and interactive websites that meet the needs of users. Elevate your web development skills with HTML5 Mastery.',
              slug: 'html',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 20,
              name: 'Django',
              title:
                'Django Mastery: Learn to Build Powerful Web Applications with a Python-based Framework',
              description:
                "Learn to build powerful web applications with Django, a high-level Python-based web framework. Our comprehensive online courses will teach you how to use Django's advanced features such as models, views, and templates to create scalable and efficient web applications. Our expert instructors will guide you in mastering the skills you need to develop full-featured web applications with Django.",
              slug: 'django',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 21,
              name: 'Angular',
              title:
                'Angular Mastery: Learn to Build Dynamic User Interfaces with a Leading JavaScript Framework',
              description:
                "Learn to build dynamic and responsive user interfaces with Angular, a leading JavaScript framework. Our comprehensive online courses will teach you how to use Angular's advanced features such as components, directives and services, to create powerful and efficient web applications. Our expert instructors will guide you in mastering the skills you need to develop high-performance web applications with Angular.",
              slug: 'anngular',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 22,
              name: 'Node JS',
              title: null,
              description: '',
              slug: 'node-js',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 23,
          name: 'Data Science',
          title:
            'Machine learning algorithms are used to process data. Improve your data scientist abilities.',
          description:
            'Learn how to build machine learning models and use them in real-world applications using Python, Big Data, Hadoop, and other tools.',
          slug: 'data-science',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 24,
              name: 'Data Analysis',
              title: null,
              description: '',
              slug: 'data-analysis',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 25,
              name: 'Deep Learning',
              title: null,
              description: '',
              slug: 'deep-learning',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 26,
              name: 'Artificial Intelligence',
              title: null,
              description: '',
              slug: 'artificial-intelligence',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 27,
              name: 'Statistics',
              title: null,
              description: '',
              slug: 'statistics',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 28,
              name: 'Big Data',
              title: null,
              description: '',
              slug: 'big-data',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 29,
              name: 'R (Programming Language)',
              title: null,
              description: '',
              slug: 'r',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 30,
              name: 'Natural Language Processing',
              title: null,
              description: '',
              slug: 'nlp',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 31,
              name: 'Machine Learning',
              title: 'Grow your skills as a data scientist.',
              description:
                'Process data with machine learning algorithms. Learn how to create machine learning models and apply them in real world applications with Python, Big Data, Hadoop and much more!',
              slug: 'machine-learning',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 32,
          name: 'Mobile Development',
          title:
            'Developing a new mobile app for Android or iOS? Anticipate the challenges of mobile application development and tap into the cloud to enhance the user experience.',
          description:
            'Mobile application development is the process to making software for smartphones and digital assistants, most commonly for Android and iOS. The software can be preinstalled on the device, downloaded from a mobile app store or accessed through a mobile web browser. The programming and markup languages used for this kind of software development include Java, Swift, C# and HTML5.',
          slug: 'mobile-development',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 33,
              name: 'Google Flutter',
              title: null,
              description: '',
              slug: 'flutter',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 34,
              name: 'iOS Development',
              title: null,
              description: '',
              slug: 'ios',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 35,
              name: 'Android Development',
              title: null,
              description: '',
              slug: 'android-development',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 36,
              name: 'React Native',
              title: null,
              description: '',
              slug: 'react-native',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 37,
          name: 'Programming Languages',
          title: null,
          description: '',
          slug: 'programming',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 38,
              name: 'Python',
              title: 'Grow your data analysis and automation with python.',
              description:
                'Often, programmers fall in love with Python because of the increased productivity it provides. Since there is no compilation step, the edit-test-debug cycle is incredibly fast.',
              slug: 'python',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 39,
              name: 'Java',
              title: 'Learn to create robust software applications with Java',
              description:
                'Java reduces costs, shortens development timeframes, drives innovation, and improves application services. With millions of developers running more than 60 billion Java Virtual Machines worldwide, Java continues to be the development platform of choice for enterprises and developers.',
              slug: 'java',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 40,
              name: 'C++',
              title: 'Create software that lasts a lifetime with C++',
              description:
                'C++ is a high-level general-purpose programming language. Created as an extension of the C programming language, or \\\\"C with Classes\\\\". The language has expanded significantly over time, and modern C++ now has object-oriented, generic, and functional features in addition to facilities for low-level memory manipulation.',
              slug: 'c-plus-plus',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 41,
              name: 'C',
              title: 'Learn to write programs for hardware devices and more',
              description:
                'C is a procedural programming language. The main features of C language include low-level access to memory, simple set of keywords, and clean style, these features make C language suitable for system programming like operating system or compiler development.',
              slug: 'c',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 42,
              name: 'C#',
              title:
                'Learn how to write any application using the C# programming language on the .NET platform.',
              description:
                'C# enables developers to build many types of secure and robust applications that run in .NET. C# has its roots in the C family of languages and will be immediately familiar to C, C++, Java, and JavaScript programmers.',
              slug: 'c-sharp',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 43,
          name: 'Game Development',
          title: 'Create 2D and 3D games in the most modern game engines available',
          description:
            'The video game industry has the highest grossing number of users and revenue in the entertainment business. Learn how to properly use Unity and Unreal engine, two of the most capable software to create simulations, games and physics.',
          slug: 'game-development',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 44,
              name: 'Unity',
              title: null,
              description: '',
              slug: 'unity',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 45,
              name: 'Unreal Engine',
              title: null,
              description: '',
              slug: 'unreal-engine',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 46,
              name: 'Game Development Fundamentals',
              title: null,
              description: '',
              slug: 'game-development-fundamentals',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 47,
              name: '2D Game Development',
              title: null,
              description: '',
              slug: '2d-game-development',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 48,
              name: '3D Game Development',
              title: null,
              description: '',
              slug: '3d-game-development',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 49,
              name: 'Blender',
              title: null,
              description: '',
              slug: 'blender',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 50,
          name: 'Database Design',
          title:
            'A properly designed database provides you with access to up-to-date, accurate information.',
          description:
            'Because a correct design is essential to achieving your goals in working with a database, investing the time required to learn the principles of good design makes sense. In the end, you are much more likely to end up with a database that meets your needs and can easily accommodate change.',
          slug: 'database-design',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 51,
              name: 'SQL',
              title: null,
              description: '',
              slug: 'sql',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 52,
              name: 'MySQL',
              title: null,
              description: '',
              slug: 'mysql',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 53,
              name: 'Oracle SQL',
              title: null,
              description: '',
              slug: 'oracle-sql',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 54,
              name: 'Database Management',
              title: null,
              description: '',
              slug: 'database-management',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 55,
              name: 'MongoDB',
              title: null,
              description: '',
              slug: 'mongodb',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 56,
              name: 'Apache Kafka',
              title: null,
              description: '',
              slug: 'apache-kafka',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 57,
              name: 'PostgreSQL',
              title: null,
              description: '',
              slug: 'postgresql',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 58,
          name: 'Software Engineering',
          title: null,
          description: '',
          slug: 'software-engineering',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 59,
              name: 'Data Structures',
              title: null,
              description: '',
              slug: 'data-sctructures',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 60,
              name: 'Algorithms',
              title: null,
              description: '',
              slug: 'algorithms',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 61,
              name: 'Microservices',
              title: null,
              description: '',
              slug: 'microservices',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 62,
              name: 'Software Architecture',
              title: null,
              description: '',
              slug: 'software-architecture',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 63,
              name: 'Software Practices',
              title: null,
              description: '',
              slug: 'software-practices',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 64,
          name: 'Software Development Tools',
          title: null,
          description: '',
          slug: 'software-development-tools',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 65,
              name: 'Git',
              title: null,
              description: '',
              slug: 'git',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 66,
              name: 'Docker',
              title: null,
              description: '',
              slug: 'docker',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 67,
              name: 'Kubernetes',
              title: null,
              description: '',
              slug: 'kubernetes',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 68,
              name: 'Github',
              title: null,
              description: '',
              slug: 'github',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 69,
              name: 'DevOps',
              title: null,
              description: '',
              slug: 'devops',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 70,
              name: 'CI/CD',
              title: null,
              description: '',
              slug: 'ci-cd',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 71,
          name: 'No-Code Development',
          title: null,
          description: '',
          slug: 'no-code-development',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 72,
              name: 'Wordpress',
              title: null,
              description: '',
              slug: 'wordpress',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 73,
              name: 'Shopify',
              title: null,
              description: '',
              slug: 'shopify',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
      ],
    },
    {
      id: 2,
      name: 'IT & Software',
      title: 'Master IT & Software Skills: Learn the Latest Technologies and Advance Your Career',
      description:
        'Discover the latest tools and techniques in IT and software development with our comprehensive online courses. From coding and programming to network security and data analysis, our expert instructors will help you master the skills you need to advance your career in the fast-paced world of technology.',
      slug: 'it-and-software',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [
        {
          id: 74,
          name: 'IT Certifications',
          title: null,
          description: '',
          slug: 'it-certifications',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 75,
              name: 'AWS Certification',
              title: null,
              description: '',
              slug: 'aws-certification',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 76,
              name: 'Microsoft Certification',
              title: null,
              description: '',
              slug: 'microsoft-certification',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 77,
              name: 'CCNA',
              title: null,
              description: '',
              slug: 'ccna',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 78,
              name: 'CEH (Certified Ethical Hacking)',
              title: null,
              description: '',
              slug: 'certified-ethical-hacking',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 79,
          name: 'Hardware',
          title: null,
          description: '',
          slug: 'hardware',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 80,
              name: 'Arduino',
              title: null,
              description: '',
              slug: 'arduino',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 81,
              name: 'Raspberry Pi',
              title: null,
              description: '',
              slug: 'raspberry-pi',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 82,
              name: 'Embedded Systems',
              title: null,
              description: '',
              slug: 'embedded-systems',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 83,
              name: 'Electronics',
              title: null,
              description: '',
              slug: 'electronics',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 84,
              name: 'Microcontroller',
              title: null,
              description: '',
              slug: 'microcontroller',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 85,
              name: 'Computer Repair',
              title: null,
              description: '',
              slug: 'computer-repair',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 86,
          name: 'Operating Systems',
          title: null,
          description: '',
          slug: 'operating-systems',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 87,
              name: 'Linux',
              title: null,
              description: '',
              slug: 'linux',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 88,
              name: 'Windows Server',
              title: null,
              description: '',
              slug: 'windows-server',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 89,
              name: 'Shell Scripting',
              title: null,
              description: '',
              slug: 'shell-scripting',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 90,
              name: 'PowerShell',
              title: null,
              description: '',
              slug: 'powershell',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 91,
              name: 'Linux Command Line',
              title: null,
              description: '',
              slug: 'linux-command-line',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 92,
          name: 'Network & Security',
          title: 'Learn to protect and penetrate servers, computers and more!',
          description:
            'Ethical hackers learn and perform hacking in a professional manner, based on the direction of the client, and later, present a maturity scorecard highlighting their overall risk and vulnerabilities and suggestions to improve.',
          slug: 'network-security',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 93,
              name: 'Ethical Hacking',
              title: null,
              description: '',
              slug: 'ethical-hacking',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 94,
              name: 'Cyber Security',
              title: null,
              description: '',
              slug: 'cyber-security',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 95,
              name: 'Penetration Testing',
              title: null,
              description: '',
              slug: 'penetration-testing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 96,
              name: 'Network Security',
              title: null,
              description: '',
              slug: 'security',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 97,
              name: 'Information Security',
              title: null,
              description: '',
              slug: 'information-security',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
      ],
    },
    {
      id: 3,
      name: 'Marketing',
      title: 'Learn Proven Strategies for Success',
      description:
        'Learn the latest tactics and strategies to take your marketing efforts to the next level. From social media and content marketing to SEO and email marketing, our expert-led courses will teach you how to create and execute effective campaigns that drive results.',
      slug: 'marketing',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [
        {
          id: 98,
          name: 'Branding',
          title: null,
          description: '',
          slug: 'branding',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 99,
              name: 'Business Branding',
              title: null,
              description: '',
              slug: 'business-branding',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 100,
              name: 'YouTube Audience Growth',
              title: null,
              description: '',
              slug: 'youtube-audience-growth',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 101,
              name: 'Personal Branding',
              title: null,
              description: '',
              slug: 'personal-branding',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 102,
              name: 'Brand Management',
              title: null,
              description: '',
              slug: 'brand-management',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 103,
              name: 'Customer Service',
              title: null,
              description: '',
              slug: 'customer-service',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 104,
          name: 'Digital Marketing',
          title: null,
          description: '',
          slug: 'digital-marketing',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 105,
              name: 'Social Media Marketing',
              title: null,
              description: '',
              slug: 'social-media-marketing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 106,
              name: 'Marketing Strategy',
              title: null,
              description: '',
              slug: 'marketing-strategy',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 107,
              name: 'Copywriting',
              title: null,
              description: '',
              slug: 'copywriting',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 108,
              name: 'Internet Marketing',
              title: null,
              description: '',
              slug: 'internet-marketing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 109,
              name: 'Email Marketing',
              title: null,
              description: '',
              slug: 'email-marketing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 110,
              name: 'Google Analytics',
              title: null,
              description: '',
              slug: 'google-analytics',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 111,
          name: 'Search Engine Optimization',
          title: null,
          description: '',
          slug: 'search-engine-optimization',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 112,
              name: 'SEO',
              title: null,
              description: '',
              slug: 'seo',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 113,
              name: 'Keyword Research',
              title: null,
              description: '',
              slug: 'keyword-research',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 114,
              name: 'Local SEO',
              title: null,
              description: '',
              slug: 'local-seo',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 115,
              name: 'Google My Business',
              title: null,
              description: '',
              slug: 'google-my-business',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 116,
              name: 'SEO Audit',
              title: null,
              description: '',
              slug: 'seo-audit',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 117,
              name: 'Link Building',
              title: null,
              description: '',
              slug: 'link-building',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 118,
              name: 'Performance Optimization',
              title: null,
              description: '',
              slug: 'performance-optimization',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 119,
          name: 'Social Media',
          title: null,
          description: '',
          slug: 'social-media',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 120,
              name: 'TikTok Marketing',
              title: null,
              description: '',
              slug: 'tiktok-marketing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 121,
              name: 'Youtube Marketing',
              title: null,
              description: '',
              slug: 'youtube-marketing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 122,
              name: 'Linkedin',
              title: null,
              description: '',
              slug: 'linkedin',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 123,
              name: 'Instagram Marketing',
              title: null,
              description: '',
              slug: 'instagram-marketing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 124,
              name: 'Facebook Ads',
              title: null,
              description: '',
              slug: 'facebook-ads',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 125,
              name: 'Facebook Marketing',
              title: null,
              description: '',
              slug: 'facebook-marketing',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 126,
              name: 'Social Media Management',
              title: null,
              description: '',
              slug: 'social-media-management',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 127,
          name: 'Marketing Fundamentals',
          title: null,
          description: '',
          slug: 'marketing-fundamentals',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 128,
              name: 'Marketing Management',
              title: null,
              description: '',
              slug: 'marketing-management',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 129,
              name: 'Marketing Psychology',
              title: null,
              description: '',
              slug: 'marketing-psychology',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 130,
              name: 'Event Planning',
              title: null,
              description: '',
              slug: 'event-planning',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 131,
              name: 'Marketing Plan',
              title: null,
              description: '',
              slug: 'marketing-plan',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 132,
              name: 'Market Research',
              title: null,
              description: '',
              slug: 'market-research',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 133,
              name: 'Marketing Analytics',
              title: null,
              description: '',
              slug: 'marketing-analytics',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 134,
          name: 'Public Relations',
          title: null,
          description: '',
          slug: 'public-relations',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 135,
              name: 'Communication Skills',
              title: null,
              description: '',
              slug: 'communication-skills',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 136,
              name: 'Media Training',
              title: null,
              description: '',
              slug: 'media-training',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 137,
              name: 'Public Speaking',
              title: null,
              description: '',
              slug: 'public-speaking',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 138,
              name: 'Podcasting',
              title: null,
              description: '',
              slug: 'podcasting',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
        {
          id: 139,
          name: 'Paid Advertising',
          title: null,
          description: '',
          slug: 'paid-advertising',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 140,
              name: 'Google Ads',
              title: null,
              description: '',
              slug: 'google-ads',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 141,
              name: 'PPC Advertising',
              title: null,
              description: '',
              slug: 'ppc-advertising',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 142,
              name: 'Retargeting',
              title: null,
              description: '',
              slug: 'retargeting',
              views: 0,
              students: 0,
              type: 'course',
            },
            {
              id: 143,
              name: 'Programmatic Advertising',
              title: null,
              description: '',
              slug: 'programmatic-advertising',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
      ],
    },
    {
      id: 4,
      name: 'Business',
      title: "Unlock Business Brilliance: Learn the Proven Strategies to Thrive in Today's Market",
      description:
        "Unlock the secrets to business success with our comprehensive online courses. From finance and leadership to sales and marketing, our expert instructors will teach you the skills and strategies you need to thrive in today's competitive market. Take your career and your business to new heights.",
      slug: 'business',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [
        {
          id: 144,
          name: 'Entrepreneurship',
          title: null,
          description: '',
          slug: 'entrepreneurship',
          views: 0,
          students: 0,
          type: 'course',
          sub_categories: [
            {
              id: 145,
              name: 'Business Fundamentals',
              title: null,
              description: '',
              slug: 'business-fundamentals',
              views: 0,
              students: 0,
              type: 'course',
            },
          ],
        },
      ],
    },
    {
      id: 5,
      name: 'Design',
      title: 'Designing Success: Master the Art of Design and Stand Out in the Crowd',
      description:
        'Learn the latest design techniques and tools to create visually stunning projects that stand out in the crowd. From graphic design and user interface design to web design and motion graphics, our expert-led courses will teach you how to bring your ideas to life and make an impact. Enhance your career and unleash your creativity with Designing Success.',
      slug: 'design',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 6,
      name: 'Lifestyle',
      title: 'Lifestyle Evolution: Enhance Your Life and Live Your Best Life',
      description:
        'Learn how to live your best life with our comprehensive lifestyle courses. From personal development and mindfulness to fitness and nutrition, our expert instructors will teach you the skills and strategies you need to create positive change and achieve your goals.',
      slug: 'lifestyle',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 7,
      name: 'Finance',
      title: 'Learn Proven Strategies to Manage Your Money and Achieve Your Goals',
      description:
        '"Discover the proven strategies to manage your money and achieve your financial goals with our comprehensive online finance courses. From investing and budgeting to personal finance and financial planning, our expert instructors will teach you how to make smart financial decisions and build a strong financial foundation.',
      slug: 'finance',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 8,
      name: 'Office Productivity',
      title: 'Boost Your Office Efficiency and Get Ahead',
      description:
        'Unlock the secrets to office productivity and get ahead with our comprehensive online courses. From time management and organization to digital tools and automation, our expert instructors will teach you how to work smarter, not harder. Boost your efficiency and effectiveness in the office and take your career to the next level.',
      slug: 'office-productivity',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 9,
      name: 'Personal Development',
      title: 'Master the Art of Self-Improvement and Achieve Your Dreams',
      description:
        'Unleash your full potential and achieve your dreams with our comprehensive personal development courses. From goal setting and self-motivation to emotional intelligence and communication skills, our expert instructors will teach you how to master the art of self-improvement and create positive change in your life.',
      slug: 'personal-development',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 10,
      name: 'Photography & Video',
      title: "Master the Art of Photography and Video to capture life's most precious moments",
      description:
        "Learn how to tell visual stories and capture life's most precious moments with our comprehensive photography and video courses. From composition and lighting to editing and post-production, our expert instructors will teach you how to create stunning images and videos that stand out from the crowd. Elevate your skills and take your passion to the next level.",
      slug: 'photography-and-video',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 11,
      name: 'Health & Fitness',
      title: 'Learn Proven Strategies for Optimal Health and Wellness',
      description:
        'Achieve optimal health and wellness with our comprehensive health and fitness courses. From nutrition and exercise to stress management and mindfulness, our expert instructors will teach you the proven strategies you need to feel great and look your best.',
      slug: 'health-and-fitness',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 12,
      name: 'Music',
      title: 'Learn the Art of Music and Unleash Your Creativity',
      description:
        'Unleash your creativity and learn the art of music with our comprehensive online courses. From playing an instrument to composing and production, our expert instructors will teach you the skills and techniques you need to bring your musical ideas to life.',
      slug: 'music',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
    {
      id: 13,
      name: 'Teaching and Academics',
      title: 'Educational Excellence: Learn Proven Strategies to Enhance Teaching and Learning',
      description:
        'Learn how to enhance teaching and learning with our comprehensive online courses. From curriculum design and classroom management to assessment and differentiated instruction, our expert instructors will teach you the proven strategies you need to be an effective educator.',
      slug: 'teaching-and-academics',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [],
    },
  ],
};
