export const categories = {
  categories: [
    {
      id: 139,
      name: 'Python',
      title: 'Grow your data analysis and automation with python.',
      description:
        'Often, programmers fall in love with Python because of the increased productivity it provides. Since there is no compilation step, the edit-test-debug cycle is incredibly fast.',
      slug: 'python',
      views: 0,
      students: 0,
      type: 'course',
    },
    {
      id: 113,
      name: 'Web Development',
      title: 'Build websites and applications with Web Development',
      description:
        'The world of web development is as wide as the internet itself. Much of our social and vocational lives play out on the internet, which prompts new industries aimed at creating, managing, and debugging the websites and applications that we increasingly rely on.',
      slug: 'web-development',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [
        {
          id: 117,
          name: 'Javascript',
          slug: 'javascript',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 124,
          name: 'React',
          slug: 'react',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 125,
          name: 'CSS',
          slug: 'css',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 128,
          name: 'Typescript',
          slug: 'typescript',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 129,
          name: 'HTML5',
          slug: 'html',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 130,
          name: 'Django',
          slug: 'django',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 126,
          name: 'Angular',
          slug: 'angular',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 127,
          name: 'Node JS',
          slug: 'node-js',
          views: 0,
          students: 0,
          type: 'course',
        },
      ],
    },
    {
      id: 117,
      name: 'Javascript',
      title: 'Grow your software development skills with JavaScript',
      description:
        'JavaScript is a text-based computer programming language used to make dynamic web pages. A must-learn for aspiring web developers or programmers, JavaScript can be used for features like image carousels, displaying countdowns and timers, and playing media on a webpage.',
      slug: 'javascript',
      views: 0,
      students: 0,
      type: 'course',
    },
    {
      id: 124,
      name: 'React',
      title: 'A JavaScript library for building user interfaces',
      description:
        'React makes it painless to create interactive UIs. Design simple views for each state in your application, and React will efficiently update and render just the right components when your data changes.',
      slug: 'react',
      views: 0,
      students: 0,
      type: 'course',
    },
    {
      id: 175,
      name: 'Network & Security',
      title: 'Learn to protect and penetrate servers, computers and more!',
      description:
        'Ethical hackers learn and perform hacking in a professional manner, based on the direction of the client, and later, present a maturity scorecard highlighting their overall risk and vulnerabilities and suggestions to improve.',
      slug: 'network-and-security',
      views: 0,
      students: 0,
      type: 'course',
      sub_categories: [
        {
          id: 176,
          name: 'Ethical Hacking',
          title: null,
          description: '',
          slug: 'ethical-hacking',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 177,
          name: 'Cyber Security',
          title: null,
          description: '',
          slug: 'cyber-security',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 178,
          name: 'Penetration Testing',
          title: null,
          description: '',
          slug: 'penetration-testing',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 179,
          name: 'Network Security',
          title: null,
          description: '',
          slug: 'network-security',
          views: 0,
          students: 0,
          type: 'course',
        },
        {
          id: 180,
          name: 'Information Security',
          title: null,
          description: '',
          slug: 'information-security',
          views: 0,
          students: 0,
          type: 'course',
        },
      ],
    },
    {
      id: 118,
      name: 'Machine Learning',
      title: 'Grow your skills as a data scientist.',
      description:
        'Process data with machine learning algorithms. Learn how to create machine learning models and apply them in real world applications with Python, Big Data, Hadoop and much more!',
      slug: 'machine-learning',
      views: 0,
      students: 0,
      type: 'course',
    },
  ],
};
