// Local Cart
export const ADD_ITEM = 'ADD_ITEM';
export const GET_TOTAL = 'GET_TOTAL';
export const GET_ITEM_TOTAL = 'GET_ITEM_TOTAL';
export const GET_ITEMS = 'GET_ITEMS';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const EMPTY_CART = 'EMPTY_CART';

export const ADD_COURSE_ITEM = 'ADD_ITEM';

export const OPEN_CART = 'OPEN_CART';
export const CLOSE_CART = 'CLOSE_CART';

// Database Cart
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const GET_TOTAL_SUCCESS = 'GET_TOTAL_SUCCESS';
export const GET_TOTAL_FAIL = 'GET_TOTAL_FAIL';
export const GET_ITEM_TOTAL_SUCCESS = 'GET_ITEM_TOTAL_SUCCESS';
export const GET_ITEM_TOTAL_FAIL = 'GET_ITEM_TOTAL_FAIL';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL';
export const SYNCH_CART_SUCCESS = 'SYNCH_CART_SUCCESS';
export const SYNCH_CART_FAIL = 'SYNCH_CART_FAIL';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL';

export const ADD_COURSE_ITEM_SUCCESS = 'ADD_COURSE_ITEM_SUCCESS';
export const ADD_COURSE_ITEM_FAIL = 'ADD_COURSE_ITEM_FAIL';

export const CHECKOUT_LOADING_SUCCESS = 'CHECKOUT_LOADING_SUCCESS';
export const CHECKOUT_LOADING_FAIL = 'CHECKOUT_LOADING_FAIL';

export const GET_PRODUCTS_FROM_LIST_SUCCESS = 'GET_PRODUCTS_FROM_LIST_SUCCESS';
export const GET_PRODUCTS_FROM_LIST_FAIL = 'GET_PRODUCTS_FROM_LIST_FAIL';
export const GET_COURSES_FROM_LIST_SUCCESS = 'GET_COURSES_FROM_LIST_SUCCESS';
export const GET_COURSES_FROM_LIST_FAIL = 'GET_COURSES_FROM_LIST_FAIL';
